from __future__ import annotations

# Keep these constants close to the database layer so future API/service code uses
# one canonical vocabulary instead of scattered string literals.

FIELD_TYPE_TEXT = "text"
FIELD_TYPE_NUMBER = "number"
FIELD_TYPE_BOOLEAN = "boolean"
FIELD_TYPE_DROPDOWN = "dropdown"
FIELD_TYPE_URL = "url"
FIELD_TYPE_UNIT_VALUE = "unit_value"

FIELD_TYPES = {
    FIELD_TYPE_TEXT,
    FIELD_TYPE_NUMBER,
    FIELD_TYPE_BOOLEAN,
    FIELD_TYPE_DROPDOWN,
    FIELD_TYPE_URL,
    FIELD_TYPE_UNIT_VALUE,
}

MOVEMENT_TYPE_CREATE = "create"
MOVEMENT_TYPE_ADJUST = "adjust"
MOVEMENT_TYPE_RESTOCK = "restock"
MOVEMENT_TYPE_RESERVE = "reserve"
MOVEMENT_TYPE_RELEASE = "release"
MOVEMENT_TYPE_CONSUME = "consume"
MOVEMENT_TYPE_DELETE = "delete"
MOVEMENT_TYPE_RESTORE = "restore"

MOVEMENT_TYPES = {
    MOVEMENT_TYPE_CREATE,
    MOVEMENT_TYPE_ADJUST,
    MOVEMENT_TYPE_RESTOCK,
    MOVEMENT_TYPE_RESERVE,
    MOVEMENT_TYPE_RELEASE,
    MOVEMENT_TYPE_CONSUME,
    MOVEMENT_TYPE_DELETE,
    MOVEMENT_TYPE_RESTORE,
}

SOURCE_MANUAL = "manual"
SOURCE_MCP = "mcp"
SOURCE_IMPORT = "import"
SOURCE_SYSTEM = "system"

SOURCES = {
    SOURCE_MANUAL,
    SOURCE_MCP,
    SOURCE_IMPORT,
    SOURCE_SYSTEM,
}

PROJECT_STATUS_DRAFT = "draft"
PROJECT_STATUS_ACTIVE = "active"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_ARCHIVED = "archived"

PROJECT_STATUSES = {
    PROJECT_STATUS_DRAFT,
    PROJECT_STATUS_ACTIVE,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_ARCHIVED,
}

RESERVATION_STATUS_ACTIVE = "active"
RESERVATION_STATUS_CONSUMED = "consumed"
RESERVATION_STATUS_RELEASED = "released"
RESERVATION_STATUS_EXPIRED = "expired"

RESERVATION_STATUSES = {
    RESERVATION_STATUS_ACTIVE,
    RESERVATION_STATUS_CONSUMED,
    RESERVATION_STATUS_RELEASED,
    RESERVATION_STATUS_EXPIRED,
}

AUDIT_ACTOR_SYSTEM = "system"
AUDIT_ACTOR_USER = "user"
AUDIT_ACTOR_MCP = "mcp"
AUDIT_ACTOR_IMPORT = "import"

AUDIT_ACTOR_TYPES = {
    AUDIT_ACTOR_SYSTEM,
    AUDIT_ACTOR_USER,
    AUDIT_ACTOR_MCP,
    AUDIT_ACTOR_IMPORT,
}

BACKUP_STATUS_CREATED = "created"
BACKUP_STATUS_FAILED = "failed"
BACKUP_STATUS_RESTORED = "restored"

BACKUP_STATUSES = {
    BACKUP_STATUS_CREATED,
    BACKUP_STATUS_FAILED,
    BACKUP_STATUS_RESTORED,
}
